#!/bin/bash

INPUT_FILE_NAME="$1"
NAME_COMPONENT=(${INPUT_FILE_NAME//./ })
FILE_NAME="${NAME_COMPONENT[0]}"
FILE_EXTENSION="${NAME_COMPONENT[1]}"
OUT_DIRECTORY="outputs"
SIZE_ARRAY=(76 120 152 167 180 1024)

mkdir -p "${OUT_DIRECTORY}"

for SIZE in "${SIZE_ARRAY[@]}"; do
    OUTPUT_FILE_NAME="${FILE_NAME}_${SIZE}.${FILE_EXTENSION}"
    OUTPUT_FILE_DIRECTORY="${OUT_DIRECTORY}/${OUTPUT_FILE_NAME}"
	java -jar generate_img.jar "${INPUT_FILE_NAME}" "${OUTPUT_FILE_DIRECTORY}" "${SIZE}" "${SIZE}"
    echo "${OUTPUT_FILE_DIRECTORY}"
done
